const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.{js,jsx,ts,tsx,vue}',
    ],
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                sm: '1.5rem',
                lg: '2rem',
                xl: '2rem',
                '2xl': '2.5rem',
            },
        },
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            borderRadius: {
                none: '0px',
                sm: '8px',
                DEFAULT: '12px',
                md: '12px',
                lg: '16px',
                xl: '20px',
                '2xl': '24px',
            },
            boxShadow: {
                md: '0 18px 40px -25px rgba(15, 23, 42, 0.35)',
            },
        },
    },
    daisyui: {
        logs: false,
        themes: [
            {
                tropical: {
                    'color-scheme': 'light',
                    primary: '#10B981',
                    secondary: '#0EA5E9',
                    accent: '#06B6D4',
                    neutral: '#0F172A',
                    'neutral-content': '#E6F6F9',
                    'base-100': '#F0FDFA',
                    'base-200': '#FFFFFF',
                    'base-300': '#E2E8F0',
                    'base-content': '#0F172A',
                    info: '#0EA5E9',
                    success: '#10B981',
                    warning: '#F59E0B',
                    error: '#F97316',
                    '--muted': '#475569',
                    '--rounded-box': '12px',
                    '--rounded-btn': '12px',
                    '--rounded-badge': '12px',
                    '--tab-radius': '0.75rem',
                },
            },
            {
                'tropical-dark': {
                    'color-scheme': 'dark',
                    primary: '#38BDF8',
                    secondary: '#6366F1',
                    accent: '#F472B6',
                    neutral: '#0F172A',
                    'neutral-content': '#E2E8F0',
                    'base-100': '#111827',
                    'base-200': '#1F2937',
                    'base-300': '#27364A',
                    'base-content': '#F8FAFC',
                    info: '#38BDF8',
                    success: '#34D399',
                    warning: '#FBBF24',
                    error: '#FB7185',
                    '--muted': '#94A3B8',
                    '--rounded-box': '12px',
                    '--rounded-btn': '12px',
                    '--rounded-badge': '12px',
                    '--tab-radius': '0.75rem',
                },
            },
            {
                'minimal-bw': {
                    'color-scheme': 'light',
                    primary: '#111827',
                    secondary: '#1F2937',
                    accent: '#6B7280',
                    neutral: '#111827',
                    'neutral-content': '#F9FAFB',
                    'base-100': '#FAFAFA',
                    'base-200': '#F4F4F5',
                    'base-300': '#E4E4E7',
                    'base-content': '#111827',
                    info: '#1F2937',
                    success: '#16A34A',
                    warning: '#F97316',
                    error: '#DC2626',
                    '--muted': '#6B7280',
                    '--rounded-box': '12px',
                    '--rounded-btn': '12px',
                    '--rounded-badge': '12px',
                    '--tab-radius': '0.75rem',
                },
            },
            {
                pastel: {
                    'color-scheme': 'light',
                    primary: '#7C3AED',
                    secondary: '#6366F1',
                    accent: '#22C55E',
                    neutral: '#0F172A',
                    'neutral-content': '#F8FAFC',
                    'base-100': '#F8FAFC',
                    'base-200': '#FFFFFF',
                    'base-300': '#E2E8F0',
                    'base-content': '#0F172A',
                    info: '#38BDF8',
                    success: '#22C55E',
                    warning: '#FACC15',
                    error: '#F97316',
                    '--muted': '#64748B',
                    '--rounded-box': '12px',
                    '--rounded-btn': '12px',
                    '--rounded-badge': '12px',
                    '--tab-radius': '0.75rem',
                },
            },
        ],
    darkTheme: 'tropical-dark',
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('daisyui'),
    ],
};
